# - Airflow Env variables.
substitutions:
  _COMPOSER_ENV_NAME: cicd-deploy
  _COMPOSER_REGION: asia-south1

# Access the id_github file from Secret Manager, and setup SSH
steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      cp known_hosts.github /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

# Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args:
    - clone
    - --recurse-submodules
    - git@github.com:git@github.com:bismay12/cicd-sonar.git
    # - checkout release1
    volumes:
    - name: 'ssh'
      path: /root/.ssh
      
# Removing the old build Dags object
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rm -r gs://asia-south1-airflow-demo-4a45701b-bucket/dags/*
        
# [START composer_cicd_dagsync_yaml]

# # install dependencies
# - name: python
#    entrypoint: pip
#    args: ["install", "-r", "requirements.txt", "--user"]

# # run
# - name: python
#    entrypoint: python
#    args: ["utils/add_dags_to_composer.py", "--dags_directory=${_DAGS_DIRECTORY}", "--dags_bucket=${_DAGS_BUCKET}"]

# Add dags to Dags folder

  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        for dagfile in $(ls dags)
          do
          gcloud composer environments storage dags import \
          --environment $_COMPOSER_ENV_NAME \
          --location $_COMPOSER_REGION \
          --source dags/$$dagfile
          done
    entrypoint: bash

#   - name: gcr.io/cloud-builders/docker
#     args:
#       - build
#       - '-t'
#       - >-
#         $_COMPOSER_REGION-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag6
#       - .
# images:
#   - >-
#     $_COMPOSER_REGION-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag6

availableSecrets:
    secretManager:
    - versionName: projects/866354246469/secrets/SSH_KEY/versions/latest
      env: 'SSH_KEY'

      
