# - Airflow Env variables.
substitutions:
  _COMPOSER_ENV_NAME: cicd-deploy
  _COMPOSER_REGION: asia-south1

# Access the id_github file from Secret Manager, and setup SSH
steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > known_hosts.github
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: ssh
        path: /root/.ssh
# Clone the repository
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'git@github.com:bismay12/cicd-sonar.git'
      - release1
    volumes:
      - name: ssh
        path: /root/.ssh
# Removing the old build Dags object
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rm -r gs://asia-south1-cicd-deploy-333a2e51-bucket/dags/*
#Add dags to Dags folder
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        for dagfile in $(ls dags)
          do
          gcloud composer environments storage dags import \
          --environment $_COMPOSER_ENV_NAME \
          --location $_COMPOSER_REGION \
          --source dags/$$dagfile
          done
    entrypoint: bash

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        $_COMPOSER_REGION-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag6
      - .
images:
  - >-
    $_COMPOSER_REGION-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag6

availableSecrets:
  secretManager:
    - versionName: projects/866354246469/secrets/SSH_KEY/versions/latest
      env: SSH_KEY

      
